apiVersion: v1
kind: Pod
metadata:
  name: lab01-pod
  namespace: lab01-ns
  labels:
    app: lab01-app
    env: lab
spec:
  containers:
    - name: echo-info
      image: ghcr.io/salimsaidhemed/k8s-labs/echo-info:latest
      ports:
        - containerPort: 8080